// Code generated by protoc-gen-go. DO NOT EDIT.
// source: graph.proto

package graph

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A Row is a single row of the dependency graph adjacency list.
type Row struct {
	// The simple name and import path of the package whose row this is.
	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImportPath string `protobuf:"bytes,2,opt,name=import_path,json=importPath,proto3" json:"import_path,omitempty"`
	// The repository where the package was defined.
	Repository string `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	// The import paths of the direct dependencies of source.
	Directs []string `protobuf:"bytes,4,rep,name=directs,proto3" json:"directs,omitempty"`
	// The names and content digests of source files in this package.
	SourceFiles          []*Row_File `protobuf:"bytes,5,rep,name=source_files,json=sourceFiles,proto3" json:"source_files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}
func (*Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e4c656902fc0e6b, []int{0}
}

func (m *Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Row.Unmarshal(m, b)
}
func (m *Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Row.Marshal(b, m, deterministic)
}
func (m *Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row.Merge(m, src)
}
func (m *Row) XXX_Size() int {
	return xxx_messageInfo_Row.Size(m)
}
func (m *Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Row proto.InternalMessageInfo

func (m *Row) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Row) GetImportPath() string {
	if m != nil {
		return m.ImportPath
	}
	return ""
}

func (m *Row) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *Row) GetDirects() []string {
	if m != nil {
		return m.Directs
	}
	return nil
}

func (m *Row) GetSourceFiles() []*Row_File {
	if m != nil {
		return m.SourceFiles
	}
	return nil
}

type Row_File struct {
	RepoPath             string   `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	Digest               []byte   `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Row_File) Reset()         { *m = Row_File{} }
func (m *Row_File) String() string { return proto.CompactTextString(m) }
func (*Row_File) ProtoMessage()    {}
func (*Row_File) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e4c656902fc0e6b, []int{0, 0}
}

func (m *Row_File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Row_File.Unmarshal(m, b)
}
func (m *Row_File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Row_File.Marshal(b, m, deterministic)
}
func (m *Row_File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row_File.Merge(m, src)
}
func (m *Row_File) XXX_Size() int {
	return xxx_messageInfo_Row_File.Size(m)
}
func (m *Row_File) XXX_DiscardUnknown() {
	xxx_messageInfo_Row_File.DiscardUnknown(m)
}

var xxx_messageInfo_Row_File proto.InternalMessageInfo

func (m *Row_File) GetRepoPath() string {
	if m != nil {
		return m.RepoPath
	}
	return ""
}

func (m *Row_File) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func init() {
	proto.RegisterType((*Row)(nil), "graph.Row")
	proto.RegisterType((*Row_File)(nil), "graph.Row.File")
}

func init() { proto.RegisterFile("graph.proto", fileDescriptor_3e4c656902fc0e6b) }

var fileDescriptor_3e4c656902fc0e6b = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xb1, 0x4a, 0xc0, 0x30,
	0x14, 0x45, 0xa9, 0x69, 0xab, 0x7d, 0x29, 0x08, 0x6f, 0x90, 0xa0, 0xa0, 0xc5, 0xa9, 0x53, 0x87,
	0x3a, 0xba, 0x3b, 0x4b, 0x7e, 0xa0, 0xc4, 0x36, 0xb6, 0x81, 0xd6, 0x17, 0x92, 0x48, 0xf1, 0x83,
	0xfd, 0x0f, 0x49, 0xa2, 0xb8, 0xdd, 0x7b, 0x6e, 0x20, 0xe7, 0x01, 0x5f, 0x9d, 0xb2, 0xdb, 0x60,
	0x1d, 0x05, 0xc2, 0x2a, 0x95, 0xc7, 0xef, 0x02, 0x98, 0xa4, 0x13, 0x11, 0xca, 0x0f, 0x75, 0x68,
	0x51, 0x74, 0x45, 0xdf, 0xc8, 0x94, 0xf1, 0x01, 0xb8, 0x39, 0x2c, 0xb9, 0x30, 0x59, 0x15, 0x36,
	0x71, 0x91, 0x26, 0xc8, 0xe8, 0x55, 0x85, 0x0d, 0xef, 0x01, 0x9c, 0xb6, 0xe4, 0x4d, 0x20, 0xf7,
	0x25, 0x58, 0xde, 0xff, 0x09, 0x0a, 0xb8, 0x5c, 0x8c, 0xd3, 0x73, 0xf0, 0xa2, 0xec, 0x58, 0xdf,
	0xc8, 0xbf, 0x8a, 0x23, 0xb4, 0x9e, 0x3e, 0xdd, 0xac, 0xa7, 0x77, 0xb3, 0x6b, 0x2f, 0xaa, 0x8e,
	0xf5, 0x7c, 0xbc, 0x1e, 0xb2, 0xa1, 0xa4, 0x73, 0x78, 0x31, 0xbb, 0x96, 0x3c, 0x3f, 0x8a, 0xd9,
	0xdf, 0x3e, 0x43, 0x19, 0x03, 0xde, 0x41, 0x13, 0xff, 0xc8, 0x52, 0xd9, 0xf7, 0x2a, 0x82, 0xa4,
	0x74, 0x03, 0xf5, 0x62, 0x56, 0xed, 0x43, 0xd2, 0x6d, 0xe5, 0x6f, 0x7b, 0xab, 0xd3, 0xd5, 0x4f,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x0f, 0x50, 0x4a, 0x04, 0x01, 0x00, 0x00,
}
