// Code generated by protoc-gen-go. DO NOT EDIT.
// source: poll.proto

package poll

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A Status records the status of a single repository.
type Status struct {
	Repository string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	RefName    string `protobuf:"bytes,2,opt,name=ref_name,json=refName,proto3" json:"ref_name,omitempty"`
	Digest     []byte `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	ErrorCount int32  `protobuf:"varint,6,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	Prefix     string `protobuf:"bytes,7,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// When the last check of this repository was made. If unset, the repository
	// has never been checked.
	LastCheck *timestamp.Timestamp `protobuf:"bytes,4,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	// The history of updates, oldest to newest.
	Updates              []*Status_Update `protobuf:"bytes,5,rep,name=updates,proto3" json:"updates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d64382c74eeea90, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *Status) GetRefName() string {
	if m != nil {
		return m.RefName
	}
	return ""
}

func (m *Status) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *Status) GetErrorCount() int32 {
	if m != nil {
		return m.ErrorCount
	}
	return 0
}

func (m *Status) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *Status) GetLastCheck() *timestamp.Timestamp {
	if m != nil {
		return m.LastCheck
	}
	return nil
}

func (m *Status) GetUpdates() []*Status_Update {
	if m != nil {
		return m.Updates
	}
	return nil
}

type Status_Update struct {
	// When this update was discovered.
	When *timestamp.Timestamp `protobuf:"bytes,1,opt,name=when,proto3" json:"when,omitempty"`
	// The digest at the time of this update.
	Digest               []byte   `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status_Update) Reset()         { *m = Status_Update{} }
func (m *Status_Update) String() string { return proto.CompactTextString(m) }
func (*Status_Update) ProtoMessage()    {}
func (*Status_Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d64382c74eeea90, []int{0, 0}
}

func (m *Status_Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status_Update.Unmarshal(m, b)
}
func (m *Status_Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status_Update.Marshal(b, m, deterministic)
}
func (m *Status_Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status_Update.Merge(m, src)
}
func (m *Status_Update) XXX_Size() int {
	return xxx_messageInfo_Status_Update.Size(m)
}
func (m *Status_Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Status_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Status_Update proto.InternalMessageInfo

func (m *Status_Update) GetWhen() *timestamp.Timestamp {
	if m != nil {
		return m.When
	}
	return nil
}

func (m *Status_Update) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func init() {
	proto.RegisterType((*Status)(nil), "poll.Status")
	proto.RegisterType((*Status_Update)(nil), "poll.Status.Update")
}

func init() { proto.RegisterFile("poll.proto", fileDescriptor_5d64382c74eeea90) }

var fileDescriptor_5d64382c74eeea90 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4f, 0x83, 0x30,
	0x14, 0xc7, 0x03, 0x63, 0xe0, 0x1e, 0x9e, 0x6a, 0x62, 0x2a, 0x07, 0x47, 0x3c, 0x71, 0xb1, 0x4b,
	0xe6, 0xc9, 0xf3, 0xee, 0xc6, 0xa0, 0x9e, 0x49, 0xc7, 0x1e, 0x8c, 0x08, 0xb4, 0x69, 0x1f, 0x51,
	0xbf, 0xa5, 0x1f, 0xc9, 0x50, 0x46, 0xc2, 0xc9, 0x5b, 0xdf, 0xff, 0xfd, 0xfe, 0x6d, 0x7e, 0x05,
	0xd0, 0xaa, 0x6d, 0x85, 0x36, 0x8a, 0x14, 0x0b, 0xc6, 0x73, 0xb2, 0xad, 0x95, 0xaa, 0x5b, 0xdc,
	0xb9, 0xec, 0x38, 0x54, 0x3b, 0x6a, 0x3a, 0xb4, 0x24, 0x3b, 0x3d, 0x61, 0x0f, 0xbf, 0x3e, 0x84,
	0x6f, 0x24, 0x69, 0xb0, 0xec, 0x1e, 0xc0, 0xa0, 0x56, 0xb6, 0x21, 0x65, 0x7e, 0xb8, 0x97, 0x7a,
	0xd9, 0x26, 0x5f, 0x24, 0xec, 0x0e, 0xae, 0x0c, 0x56, 0x45, 0x2f, 0x3b, 0xe4, 0xbe, 0xdb, 0x46,
	0x06, 0xab, 0x17, 0xd9, 0x21, 0xbb, 0x85, 0xf0, 0xd4, 0xd4, 0x68, 0x89, 0xaf, 0x52, 0x2f, 0xbb,
	0xce, 0x2f, 0x13, 0xdb, 0x42, 0x8c, 0xc6, 0x28, 0x53, 0x94, 0x6a, 0xe8, 0x89, 0x87, 0xa9, 0x97,
	0xad, 0x73, 0x70, 0xd1, 0x61, 0x4c, 0xc6, 0xa2, 0x36, 0x58, 0x35, 0xdf, 0x3c, 0x72, 0x37, 0x5e,
	0x26, 0xf6, 0x0c, 0xd0, 0x4a, 0x4b, 0x45, 0x79, 0xc6, 0xf2, 0x93, 0x07, 0xa9, 0x97, 0xc5, 0xfb,
	0x44, 0x4c, 0x32, 0x62, 0x96, 0x11, 0xef, 0xb3, 0x4c, 0xbe, 0x19, 0xe9, 0xc3, 0x08, 0xb3, 0x47,
	0x88, 0x06, 0x7d, 0x92, 0x84, 0x96, 0xaf, 0xd3, 0x55, 0x16, 0xef, 0x6f, 0x84, 0xfb, 0x96, 0xc9,
	0x52, 0x7c, 0xb8, 0x5d, 0x3e, 0x33, 0xc9, 0x2b, 0x84, 0x53, 0xc4, 0x04, 0x04, 0x5f, 0x67, 0xec,
	0x9d, 0xf9, 0xff, 0xaf, 0x39, 0x6e, 0x21, 0xed, 0x2f, 0xa5, 0x8f, 0xa1, 0x6b, 0x3c, 0xfd, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xf8, 0x44, 0x31, 0xf1, 0x8e, 0x01, 0x00, 0x00,
}
